# Generated by Django 5.0.6 on 2024-05-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_is_active_appuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('image', models.BinaryField()),
                ('director', models.CharField(max_length=40)),
                ('minage', models.IntegerField()),
                ('production', models.CharField(max_length=40)),
                ('originallanguage', models.CharField(max_length=40)),
                ('rank', models.IntegerField()),
                ('moviecategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.moviecategory')),
            ],
        ),
    ]
