# Generated by Django 5.0.6 on 2024-05-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_moviecategory_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
