# Generated by Django 5.0.6 on 2024-05-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_rename_movies_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('movie_screening_id', models.IntegerField()),
            ],
            options={
                'db_table': 'AvailableSeats',
                'managed': False,
            },
        ),
    ]
