# Generated by Django 5.0.6 on 2024-05-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_testview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieScreening',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('price_standard', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movie_hall', models.IntegerField()),
                ('three_dimensional', models.BooleanField()),
                ('language', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'moviescreening',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieScreeningSeat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
            options={
                'db_table': 'moviescreeningseats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('ordered_on_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AvailableSeat',
        ),
        migrations.DeleteModel(
            name='TestView',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moviecategory',
            options={'managed': False},
        ),
    ]
