# Generated by Django 5.0.6 on 2024-05-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_moviescreening_moviescreeningseat_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
        migrations.AlterModelTable(
            name='moviecategory',
            table='moviecategories',
        ),
    ]
