# Generated by Django 5.0.6 on 2024-05-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_alter_movie_table_alter_moviecategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(db_column='seatnumber')),
            ],
            options={
                'db_table': 'availableseats',
                'managed': False,
            },
        ),
    ]
